# Generated by Django 2.2.17 on 2021-01-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=64, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=64, verbose_name='name')),
                ('working_seniority', models.DateField(auto_now_add=True, help_text='从业时间', verbose_name='working seniority')),
                ('fund_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_fund_company', to='oauth.FundCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=64, unique=True, verbose_name='name')),
                ('code', models.CharField(help_text='基金代码', max_length=32, unique=True, verbose_name='name')),
                ('type', models.CharField(help_text='基金类型', max_length=32, verbose_name='type')),
                ('scale', models.FloatField(help_text='基金规模:亿元', verbose_name='scale')),
                ('found_date', models.DateField(auto_now_add=True, help_text='成立日', verbose_name='found date')),
                ('custodian', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_custodian', to='oauth.FundCompany')),
                ('managers', models.ManyToManyField(blank=True, default=None, to='oauth.FundManager')),
            ],
        ),
    ]
