# Generated by Django 2.2.17 on 2021-01-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_fund_fundcompany_fundmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundcompany',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='fundmanager',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='fund',
            table='fund',
        ),
        migrations.AlterModelTable(
            name='fundcompany',
            table='fund_company',
        ),
        migrations.AlterModelTable(
            name='fundmanager',
            table='fund_manager',
        ),
    ]
