# Generated by Django 2.2.17 on 2021-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20210128_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='found_date',
            field=models.DateField(help_text='成立日', verbose_name='found date'),
        ),
        migrations.AlterField(
            model_name='fundmanager',
            name='working_seniority',
            field=models.DateField(help_text='从业时间', verbose_name='working seniority'),
        ),
    ]
