# Generated by Django 2.2.17 on 2021-01-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20210128_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'fund'},
        ),
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='日期', verbose_name='date')),
                ('principal', models.FloatField(help_text='本金', verbose_name='principal')),
                ('amount', models.FloatField(help_text='金额', verbose_name='amount')),
                ('fund_net', models.FloatField(help_text='基金净值', verbose_name='fund net')),
                ('share', models.FloatField(help_text='基金份额', verbose_name='fund share')),
                ('fund', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref_fund', to='oauth.Fund')),
            ],
            options={
                'verbose_name': 'fund account',
                'db_table': 'fund_account',
            },
        ),
    ]
